name: DeployFirstSveltkitCpanel
# https://appimate.medium.com/cicd-with-cpanel-and-github-c6a3a5560821
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: first
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/chekout@v2

    - name: Sync files
      uses: SamKirkland/sddjdj
      with:
        server: ftp.iflexico
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: /
      
