name: DeployFirstSveltkitCpanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: first
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/chekout@v2

    - name: Sync files
      uses: SamKirkland/
      
